//Audition
export const CHECK_WORD = 'CHECK_WORD'
export const INIT_AUDITION = 'INIT_AUDITION'
export const SET_AUDIO_FILE_PROGRESS = 'SET_AUDIO_FILE_PROGRESS'
export const END_AUDITION = 'END_AUDITION'
export const LOAD_USER_SONGS = 'LOAD_USER_SONGS'


//UI
export const LOADING_AUDITION_TEXT_REQUEST = 'LOADING_AUDITION_TEXT_REQUEST'
export const LOADING_AUDITION_TEXT_SUCCESS = 'LOADING_AUDITION_TEXT_SUCCESS'
export const LOADING_AUDITION_TEXT_ERROR = 'LOADING_AUDITION_TEXT_ERROR'
