export const MEDIA_LIBRARY_LAST_MODIFIED = 'MEDIA_LIBRARY_LAST_MODIFIED'
export const MEDIA_LIBRARY_ITEMS = 'MEDIA_LIBRARY_ITEMS'
export const STATE = 'STATE'
export const STATE_VERSION = 'STATE_VERSION'
